[package]
name = "microsoft_security_utilities_core_ffi"
version = "1.4.25"
edition = "2021"

[lib]
name = "microsoft_security_utilities_core"
crate-type = ["dylib"]

[dependencies]
microsoft_security_utilities_core = { path = "../security_utilities_rust" }
