// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
using System;
using System.Collections.Generic;

namespace Microsoft.Security.Utilities
{
    public class Guid : RegexPattern
    {
        public Guid()
        {
            Id = "DAT101/000";
            Name = nameof(Guid);
            Pattern = @"(?i)^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$";
        }

        public override IEnumerable<string> GenerateTruePositiveExamples()
        {
            // Example with all lower case as generated by built-in VS GUID tool.
            yield return "150777be-a4c0-4609-9d13-c539a86e8705";

            // Example with all UPPER case.
            yield return "150777BE-A4C0-4609-9D13-C539A86E8705";

            // Example of a GUID, but not a UUID. This example is the Office 365 SharePoint Online App Id. See https://learn.microsoft.com/en-us/troubleshoot/entra/entra-id/governance/verify-first-party-apps-sign-in.
            yield return "00000003-0000-0ff1-ce00-000000000000";

            yield return System.Guid.NewGuid().ToString();
        }
    }
}
