// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Microsoft.Security.Utilities;

public enum AzureCognitiveService
{
    AzureAIServices = 0,
    AzureOpenAI = 1,
    AzureAnomalyDetectorEE = 2,
    AzureAnomalyDetector = 3,
    AzureCognitiveServices = 4,
    AzureComputerVision = 5,
    AzureContentModerator = 6,
    AzureContentSafety = 7,
    AzureCustomVisionPrediction = 8,
    AzureCustomVisionTraining = 9,
    AzureFace = 10,
    AzureFormRecognizer = 11,
    AzureHealthDecisionSupport = 12,
    AzureHealthInsights = 13,
    AzureImmersiveReader = 14,
    AzureInternalAllInOne = 15,
    AzureKnowledge = 16,
    AzureLuisAuthoring = 17,
    AzureLuis = 18,
    AzureMetricsAdvisor = 19,
    AzurePersonalizer = 20,
    AzureQnAMaker = 21,
    AzureQnAMakerV2 = 22,
    AzureSpeakerRecognition = 23,
    AzureSpeechServices = 24,
    AzureSpeechTranslation = 25,
    AzureTextAnalytics = 26,
    AzureTextTranslation = 27,
    AzureDummy = 28,
    AzureTranscriptionIntelligence = 29,
    AzureVideoIntelligence = 30,
    AzureBingAutosuggest = 31,
    AzureBingAutosuggestV7 = 32,
    AzureBingCustomSearch = 33,
    AzureBingCustomVisualSearch = 34,
    AzureBingEntitySearch = 35,
    AzureBingSearch = 36,
    AzureBingSearchV7 = 37,
    AzureBingSpeech = 38,
    AzureBingSpellCheck = 39,
    AzureBingSpellCheckV7 = 40,
}
