name: Test .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test .NET
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Nerdbank Git Versioning used by this project
        # requires full clone (i.e. not the shallow default of GitHub Actions)
        fetch-depth: 0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.100'
    - name: Build
      run: ./BuildAndTest.cmd
