name: Test .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    name: Test .NET
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Nerdbank Git Versioning used by this project
        # requires full clone (i.e. not the shallow default of GitHub Actions)
        fetch-depth: 0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Show dotnet info
      run: dotnet --info

    - name: Build
      run: ./BuildAndTest.cmd -Configuration ${{matrix.configuration}}

