name: Test Rust

on:
  push:
    branches: [ "main", "release/**" ]
  pull_request:
    branches: [ "main", "release/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test Rust implementations on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src/security_utilities_rust
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
